<template>
  <div class="chat-window">
    <div class="chat-messages">
      <div
        v-for="(message, index) in messages"
        :key="index"
        :class="{'user-message': message.isUser}"
      >
        {{ message.text }}
      </div>
    </div>
    <input
      v-model="userInput"
      placeholder="Type a message..."
      @keyup.enter="confirmSearch"
    >
  </div>
</template>

<script lang="ts">

import { Component, Vue } from 'vue-property-decorator'
const searchConditions = require('./search_conditions.json')
@Component

export default class AISearchWindow extends Vue {
  public messages: {text: string, isUser: Boolean}[] = []
  private userInput: string = ''
  public lastInput: string = ''
  private Conditions: any[] = searchConditions.children

  public sendMessage () {
    const userMessage = this.userInput
    if (userMessage) {
      this.messages.push({ text: userMessage, isUser: true })
      this.lastInput = userMessage
      this.userInput = ''
      this.addResponseFromAPI(userMessage)
    }
  }

  public addResponseFromAPI (Response: string) {
    // Simulate a response from an API (replace with your actual API call)
    if (Response !== this.lastInput) {
      const responseMessage = 'SEU-Allen: ' + Response
      this.messages.push({ text: responseMessage, isUser: false })
    }
  }

  // public addResponseFromAPI (Response: string) {
  //   // Simulate a response from an API (replace with your actual API call)
  //   if (Response !== this.lastInput) {
  //     const responseMessage = 'Response: ' + Response
  //     this.messages.push({ text: responseMessage, isUser: false })
  //   }
  // }

  public confirmSearch () {
    this.$emit('AISearch')
  }

  public GetIntent (question:string, searchIntent:string) {
    let conditions:any = {}
    for (const index in conditions) {
      console.log(index)
      // for (const sc in conditions[index].children) {
      //   console.log(sc)
      // }
    }
    // 定义用于搜索意图的关键词
    const searchKeywords = ['search', 'find', 'query', 'inquire', 'look for']
    const altasKeywords = ['fMOST', 'CCFv3']
    const dataSourceKeywords = ['SEU', 'AIBS', 'Mouselight']
    const ReconMethodKeywords = [
      'auto_r',
      'semi_r',
      'manual'
    ]
    const brainRigionKeywords = [
      'FRP',
      'FRP Layer1',
      'FRP Layer5',
      'FRP Layer6a',
      'MOp',
      'MOp Layer1',
      'MOp Layer2/3',
      'MOp Layer5',
      'MOp Layer6',
      'MOp Layer6a',
      'MOp Layer6b',
      'MOs',
      'MOs Layer1',
      'MOs Layer2/3',
      'MOs Layer5',
      'MOs Layer6',
      'MOs Layer6a',
      'MOs Layer6b',
      'SSp Layer6',
      'SSp-n',
      'SSp-n Layer1',
      'SSp-n Layer2/3',
      'SSp-n Layer4',
      'SSp-n Layer5',
      'SSp-n Layer6',
      'SSp-n Layer6a',
      'SSp-n Layer6b',
      'SSp-bfd',
      'SSp-bfd Layer1',
      'SSp-bfd Layer2/3',
      'SSp-bfd Layer4',
      'SSp-bfd Layer5',
      'SSp-bfd Layer6',
      'SSp-bfd Layer6a',
      'SSp-bfd Layer6b',
      'SSp-ll',
      'SSp-ll Layer1',
      'SSp-ll Layer2/3',
      'SSp-ll Layer4',
      'SSp-ll Layer5',
      'SSp-ll Layer6',
      'SSp-ll Layer6a',
      'SSp-m',
      'SSp-m Layer1',
      'SSp-m Layer2/3',
      'SSp-m Layer4',
      'SSp-m Layer5',
      'SSp-m Layer6',
      'SSp-m Layer6a',
      'SSp-m Layer6b',
      'SSp-ul',
      'SSp-ul Layer1',
      'SSp-ul Layer2/3',
      'SSp-ul Layer4',
      'SSp-ul Layer5',
      'SSp-ul Layer6a',
      'SSp-tr',
      'SSp-tr Layer1',
      'SSp-tr Layer2/3',
      'SSp-tr Layer4',
      'SSp-tr Layer5',
      'SSp-tr Layer6a',
      'SSp-un',
      'SSp-un Layer1',
      'SSp-un Layer2/3',
      'SSp-un Layer4',
      'SSp-un Layer5',
      'SSp-un Layer6',
      'SSp-un Layer6a',
      'SSp-un Layer6b',
      'SSs',
      'SSs Layer1',
      'SSs Layer2/3',
      'SSs Layer4',
      'SSs Layer5',
      'SSs Layer6',
      'SSs Layer6a',
      'SSs Layer6b',
      'GU',
      'GU Layer1',
      'GU Layer2/3',
      'GU Layer4',
      'GU Layer5',
      'GU Layer6',
      'GU Layer6a',
      'GU Layer6b',
      'VISC',
      'VISC Layer1',
      'VISC Layer2/3',
      'VISC Layer4',
      'VISC Layer5',
      'VISC Layer6',
      'VISC Layer6a',
      'VISC Layer6b',
      'AUDd',
      'AUDd Layer1',
      'AUDd Layer2/3',
      'AUDd Layer4',
      'AUDd Layer5',
      'AUDd Layer6',
      'AUDd Layer6a',
      'AUDp',
      'AUDp Layer1',
      'AUDp Layer2/3',
      'AUDp Layer4',
      'AUDp Layer5',
      'AUDp Layer6',
      'AUDp Layer6a',
      'AUDpo',
      'AUDpo Layer1',
      'AUDpo Layer2/3',
      'AUDpo Layer4',
      'AUDpo Layer5',
      'AUDpo Layer6',
      'AUDv',
      'AUDv Layer1',
      'AUDv Layer2/3',
      'AUDv Layer4',
      'AUDv Layer5',
      'AUDv Layer6',
      'AUDv Layer6a',
      'VISal',
      'VISal Layer1',
      'VISal Layer2/3',
      'VISal Layer4',
      'VISal Layer5',
      'VISal Layer6',
      'VISal Layer6a',
      'VISam',
      'VISam Layer2/3',
      'VISam Layer4',
      'VISam Layer5',
      'VISam Layer6a',
      'VISl',
      'VISl Layer1',
      'VISl Layer2/3',
      'VISl Layer4',
      'VISl Layer5',
      'VISl Layer6',
      'VISl Layer6a',
      'VISl Layer6b',
      'VISp',
      'VISp Layer1',
      'VISp Layer2/3',
      'VISp Layer4',
      'VISp Layer5',
      'VISp Layer6',
      'VISp Layer6a',
      'VISp Layer6b',
      'VISpl',
      'VISpl Layer1',
      'VISpl Layer2/3',
      'VISpl Layer4',
      'VISpl Layer5',
      'VISpl Layer6a',
      'VISpm',
      'VISpm Layer1',
      'VISpm Layer2/3',
      'VISpm Layer4',
      'VISpm Layer5',
      'VISpm Layer6a',
      'VISli',
      'VISli Layer1',
      'VISli Layer2/3',
      'VISli Layer4',
      'VISli Layer5',
      'VISli Layer6a',
      'VISpor',
      'VISpor Layer1',
      'VISpor Layer2/3',
      'VISpor Layer4',
      'VISpor Layer5',
      'VISpor Layer6a',
      'ACAd',
      'ACAd Layer1',
      'ACAd Layer2/3',
      'ACAd Layer5',
      'ACAd Layer6',
      'ACAd Layer6a',
      'ACAv',
      'ACAv Layer1',
      'ACAv Layer2/3',
      'ACAv Layer5',
      'ACAv Layer6a',
      'PL',
      'PL Layer1',
      'PL Layer2/3',
      'PL Layer5',
      'PL Layer6a',
      'ILA',
      'ILA Layer2/3',
      'ILA Layer5',
      'ORBl',
      'ORBl Layer1',
      'ORBl Layer2/3',
      'ORBl Layer5',
      'ORBl Layer6',
      'ORBl Layer6a',
      'ORBl Layer6b',
      'ORBm',
      'ORBm Layer1',
      'ORBm Layer2/3',
      'ORBm Layer5',
      'ORBvl',
      'ORBvl Layer1',
      'ORBvl Layer2/3',
      'ORBvl Layer5',
      'ORBvl Layer6a',
      'AId',
      'AId Layer1',
      'AId Layer2/3',
      'AId Layer5',
      'AId Layer6',
      'AId Layer6a',
      'AId Layer6b',
      'AIp',
      'AIp Layer1',
      'AIp Layer2/3',
      'AIp Layer5',
      'AIp Layer6',
      'AIp Layer6a',
      'AIv',
      'AIv Layer1',
      'AIv Layer2/3',
      'AIv Layer5',
      'AIv Layer6a',
      'RSPagl',
      'RSPagl Layer1',
      'RSPagl Layer2/3',
      'RSPagl Layer5',
      'RSPagl Layer6a',
      'RSPd',
      'RSPd Layer1',
      'RSPd Layer2/3',
      'RSPd Layer5',
      'RSPd Layer6a',
      'RSPv',
      'RSPv Layer1',
      'RSPv Layer2/3',
      'RSPv Layer5',
      'RSPv Layer6a',
      'VISa',
      'VISa Layer1',
      'VISa Layer2/3',
      'VISa Layer4',
      'VISa Layer5',
      'VISrl',
      'VISrl Layer1',
      'VISrl Layer2/3',
      'VISrl Layer4',
      'VISrl Layer5',
      'VISrl Layer6',
      'VISrl Layer6a',
      'TEa',
      'TEa Layer1',
      'TEa Layer2/3',
      'TEa Layer4',
      'TEa Layer5',
      'TEa Layer6',
      'TEa Layer6a',
      'PERI',
      'PERI Layer2/3',
      'PERI Layer5',
      'PERI Layer6a',
      'ECT',
      'ECT Layer1',
      'ECT Layer2/3',
      'ECT Layer5',
      'ECT Layer6',
      'ECT Layer6a',
      'ECT Layer6b',
      'MOB',
      'AOB',
      'AON',
      'TT',
      'DP',
      'PIR',
      'NLOT',
      'COAa',
      'COAp',
      'PAA',
      'TR',
      'HPF',
      'CA1',
      'CA2',
      'CA3',
      'DG',
      'IG',
      'ENTl',
      'ENTm',
      'PAR',
      'POST',
      'PRE',
      'SUB',
      'ProS',
      'HATA',
      'APr',
      'CLA',
      'EPd',
      'EPv',
      'LA',
      'BLA',
      'BMA',
      'PA',
      'CP',
      'ACB',
      'FS',
      'OT',
      'LSc',
      'LSr',
      'LSv',
      'SF',
      'AAA',
      'CEA',
      'IA',
      'MEA',
      'PAL',
      'GPe',
      'GPi',
      'SI',
      'MA',
      'MS',
      'NDB',
      'TRS',
      'BST',
      'BS',
      'TH',
      'VAL',
      'VM',
      'VPL',
      'VPLpc',
      'VPM',
      'VPMpc',
      'PoT',
      'SPFp',
      'PP',
      'MG',
      'LGd',
      'LP',
      'PO',
      'POL',
      'SGN',
      'AV',
      'AM',
      'AD',
      'IAD',
      'LD',
      'IMD',
      'MD',
      'SMT',
      'PR',
      'PVT',
      'PT',
      'RE',
      'Xi',
      'CM',
      'PCN',
      'CL',
      'PF',
      'PIL',
      'RT',
      'IGL',
      'LGv',
      'HY',
      'PVH',
      'PVi',
      'ARH',
      'DMH',
      'MPO',
      'SBPV',
      'SCH',
      'AHN',
      'MM',
      'Mmme',
      'Mml',
      'Mmd',
      'SUM',
      'TMv',
      'MPN',
      'PMd',
      'VMH',
      'PH',
      'LHA',
      'LPO',
      'PSTN',
      'PeF',
      'TU',
      'ZI',
      'MB',
      'SCs',
      'IC',
      'SNr',
      'VTA',
      'MRN',
      'SCm',
      'PAG',
      'APN',
      'NOT',
      'NPC',
      'PPT',
      'CUN',
      'RN',
      'AT',
      'SNc',
      'PPN',
      'IPN',
      'DR',
      'P',
      'NLL',
      'PSV',
      'PB',
      'SOC',
      'B',
      'DTN',
      'PCG',
      'PG',
      'PRNc',
      'SUT',
      'TRN',
      'V',
      'P5',
      'PC5',
      'CS',
      'LDT',
      'NI',
      'PRNr',
      'RPO',
      'MY',
      'DCO',
      'VCO',
      'CU',
      'SPVC',
      'SPVI',
      'VII',
      'DMX',
      'GRN',
      'IO',
      'IRN',
      'LRN',
      'MARN',
      'MDRN',
      'MDRNd',
      'MDRNv',
      'PARN',
      'PGRNd',
      'PGRNl',
      'PRP',
      'PPY',
      'LAV',
      'MV',
      'SPIV',
      'SUV',
      'RM',
      'CENT',
      'CUL',
      'CUL4, 5',
      'DEC',
      'FOTU',
      'PYR',
      'UVU',
      'NOD',
      'SIM',
      'AN',
      'PRM',
      'COPY',
      'PFL',
      'FL',
      'FN',
      'fiber tracts',
      'mlf',
      'll',
      'arb',
      'fa',
      'ccg',
      'fp',
      'ccb',
      'int',
      'or',
      'nst',
      'tspc',
      'cing',
      'alv',
      'fi',
      'fx',
      'dhc',
      'mfb',
      'pm',
      'mtt',
      'sm',
      'fr',
      'unknown'
    ]
    const projKeywords = [
      'FRP',
      'FRP Layer1',
      'FRP Layer5',
      'FRP Layer6a',
      'MOp',
      'MOp Layer1',
      'MOp Layer2/3',
      'MOp Layer5',
      'MOp Layer6',
      'MOp Layer6a',
      'MOp Layer6b',
      'MOs',
      'MOs Layer1',
      'MOs Layer2/3',
      'MOs Layer5',
      'MOs Layer6',
      'MOs Layer6a',
      'MOs Layer6b',
      'SSp Layer6',
      'SSp-n',
      'SSp-n Layer1',
      'SSp-n Layer2/3',
      'SSp-n Layer4',
      'SSp-n Layer5',
      'SSp-n Layer6',
      'SSp-n Layer6a',
      'SSp-n Layer6b',
      'SSp-bfd',
      'SSp-bfd Layer1',
      'SSp-bfd Layer2/3',
      'SSp-bfd Layer4',
      'SSp-bfd Layer5',
      'SSp-bfd Layer6',
      'SSp-bfd Layer6a',
      'SSp-bfd Layer6b',
      'SSp-ll',
      'SSp-ll Layer1',
      'SSp-ll Layer2/3',
      'SSp-ll Layer4',
      'SSp-ll Layer5',
      'SSp-ll Layer6',
      'SSp-ll Layer6a',
      'SSp-m',
      'SSp-m Layer1',
      'SSp-m Layer2/3',
      'SSp-m Layer4',
      'SSp-m Layer5',
      'SSp-m Layer6',
      'SSp-m Layer6a',
      'SSp-m Layer6b',
      'SSp-ul',
      'SSp-ul Layer1',
      'SSp-ul Layer2/3',
      'SSp-ul Layer4',
      'SSp-ul Layer5',
      'SSp-ul Layer6a',
      'SSp-tr',
      'SSp-tr Layer1',
      'SSp-tr Layer2/3',
      'SSp-tr Layer4',
      'SSp-tr Layer5',
      'SSp-tr Layer6a',
      'SSp-un',
      'SSp-un Layer1',
      'SSp-un Layer2/3',
      'SSp-un Layer4',
      'SSp-un Layer5',
      'SSp-un Layer6',
      'SSp-un Layer6a',
      'SSp-un Layer6b',
      'SSs',
      'SSs Layer1',
      'SSs Layer2/3',
      'SSs Layer4',
      'SSs Layer5',
      'SSs Layer6',
      'SSs Layer6a',
      'SSs Layer6b',
      'GU',
      'GU Layer1',
      'GU Layer2/3',
      'GU Layer4',
      'GU Layer5',
      'GU Layer6',
      'GU Layer6a',
      'GU Layer6b',
      'VISC',
      'VISC Layer1',
      'VISC Layer2/3',
      'VISC Layer4',
      'VISC Layer5',
      'VISC Layer6',
      'VISC Layer6a',
      'VISC Layer6b',
      'AUDd',
      'AUDd Layer1',
      'AUDd Layer2/3',
      'AUDd Layer4',
      'AUDd Layer5',
      'AUDd Layer6',
      'AUDd Layer6a',
      'AUDp',
      'AUDp Layer1',
      'AUDp Layer2/3',
      'AUDp Layer4',
      'AUDp Layer5',
      'AUDp Layer6',
      'AUDp Layer6a',
      'AUDpo',
      'AUDpo Layer1',
      'AUDpo Layer2/3',
      'AUDpo Layer4',
      'AUDpo Layer5',
      'AUDpo Layer6',
      'AUDv',
      'AUDv Layer1',
      'AUDv Layer2/3',
      'AUDv Layer4',
      'AUDv Layer5',
      'AUDv Layer6',
      'AUDv Layer6a',
      'VISal',
      'VISal Layer1',
      'VISal Layer2/3',
      'VISal Layer4',
      'VISal Layer5',
      'VISal Layer6',
      'VISal Layer6a',
      'VISam',
      'VISam Layer2/3',
      'VISam Layer4',
      'VISam Layer5',
      'VISam Layer6a',
      'VISl',
      'VISl Layer1',
      'VISl Layer2/3',
      'VISl Layer4',
      'VISl Layer5',
      'VISl Layer6',
      'VISl Layer6a',
      'VISl Layer6b',
      'VISp',
      'VISp Layer1',
      'VISp Layer2/3',
      'VISp Layer4',
      'VISp Layer5',
      'VISp Layer6',
      'VISp Layer6a',
      'VISp Layer6b',
      'VISpl',
      'VISpl Layer1',
      'VISpl Layer2/3',
      'VISpl Layer4',
      'VISpl Layer5',
      'VISpl Layer6a',
      'VISpm',
      'VISpm Layer1',
      'VISpm Layer2/3',
      'VISpm Layer4',
      'VISpm Layer5',
      'VISpm Layer6a',
      'VISli',
      'VISli Layer1',
      'VISli Layer2/3',
      'VISli Layer4',
      'VISli Layer5',
      'VISli Layer6a',
      'VISpor',
      'VISpor Layer1',
      'VISpor Layer2/3',
      'VISpor Layer4',
      'VISpor Layer5',
      'VISpor Layer6a',
      'ACAd',
      'ACAd Layer1',
      'ACAd Layer2/3',
      'ACAd Layer5',
      'ACAd Layer6',
      'ACAd Layer6a',
      'ACAv',
      'ACAv Layer1',
      'ACAv Layer2/3',
      'ACAv Layer5',
      'ACAv Layer6a',
      'PL',
      'PL Layer1',
      'PL Layer2/3',
      'PL Layer5',
      'PL Layer6a',
      'ILA',
      'ILA Layer2/3',
      'ILA Layer5',
      'ORBl',
      'ORBl Layer1',
      'ORBl Layer2/3',
      'ORBl Layer5',
      'ORBl Layer6',
      'ORBl Layer6a',
      'ORBl Layer6b',
      'ORBm',
      'ORBm Layer1',
      'ORBm Layer2/3',
      'ORBm Layer5',
      'ORBvl',
      'ORBvl Layer1',
      'ORBvl Layer2/3',
      'ORBvl Layer5',
      'ORBvl Layer6a',
      'AId',
      'AId Layer1',
      'AId Layer2/3',
      'AId Layer5',
      'AId Layer6',
      'AId Layer6a',
      'AId Layer6b',
      'AIp',
      'AIp Layer1',
      'AIp Layer2/3',
      'AIp Layer5',
      'AIp Layer6',
      'AIp Layer6a',
      'AIv',
      'AIv Layer1',
      'AIv Layer2/3',
      'AIv Layer5',
      'AIv Layer6a',
      'RSPagl',
      'RSPagl Layer1',
      'RSPagl Layer2/3',
      'RSPagl Layer5',
      'RSPagl Layer6a',
      'RSPd',
      'RSPd Layer1',
      'RSPd Layer2/3',
      'RSPd Layer5',
      'RSPd Layer6a',
      'RSPv',
      'RSPv Layer1',
      'RSPv Layer2/3',
      'RSPv Layer5',
      'RSPv Layer6a',
      'VISa',
      'VISa Layer1',
      'VISa Layer2/3',
      'VISa Layer4',
      'VISa Layer5',
      'VISrl',
      'VISrl Layer1',
      'VISrl Layer2/3',
      'VISrl Layer4',
      'VISrl Layer5',
      'VISrl Layer6',
      'VISrl Layer6a',
      'TEa',
      'TEa Layer1',
      'TEa Layer2/3',
      'TEa Layer4',
      'TEa Layer5',
      'TEa Layer6',
      'TEa Layer6a',
      'PERI',
      'PERI Layer2/3',
      'PERI Layer5',
      'PERI Layer6a',
      'ECT',
      'ECT Layer1',
      'ECT Layer2/3',
      'ECT Layer5',
      'ECT Layer6',
      'ECT Layer6a',
      'ECT Layer6b',
      'MOB',
      'AOB',
      'AON',
      'TT',
      'DP',
      'PIR',
      'NLOT',
      'COAa',
      'COAp',
      'PAA',
      'TR',
      'HPF',
      'CA1',
      'CA2',
      'CA3',
      'DG',
      'IG',
      'ENTl',
      'ENTm',
      'PAR',
      'POST',
      'PRE',
      'SUB',
      'ProS',
      'HATA',
      'APr',
      'CLA',
      'EPd',
      'EPv',
      'LA',
      'BLA',
      'BMA',
      'PA',
      'CP',
      'ACB',
      'FS',
      'OT',
      'LSc',
      'LSr',
      'LSv',
      'SF',
      'AAA',
      'CEA',
      'IA',
      'MEA',
      'PAL',
      'GPe',
      'GPi',
      'SI',
      'MA',
      'MS',
      'NDB',
      'TRS',
      'BST',
      'BS',
      'TH',
      'VAL',
      'VM',
      'VPL',
      'VPLpc',
      'VPM',
      'VPMpc',
      'PoT',
      'SPFp',
      'PP',
      'MG',
      'LGd',
      'LP',
      'PO',
      'POL',
      'SGN',
      'AV',
      'AM',
      'AD',
      'IAD',
      'LD',
      'IMD',
      'MD',
      'SMT',
      'PR',
      'PVT',
      'PT',
      'RE',
      'Xi',
      'CM',
      'PCN',
      'CL',
      'PF',
      'PIL',
      'RT',
      'IGL',
      'LGv',
      'HY',
      'PVH',
      'PVi',
      'ARH',
      'DMH',
      'MPO',
      'SBPV',
      'SCH',
      'AHN',
      'MM',
      'Mmme',
      'Mml',
      'Mmd',
      'SUM',
      'TMv',
      'MPN',
      'PMd',
      'VMH',
      'PH',
      'LHA',
      'LPO',
      'PSTN',
      'PeF',
      'TU',
      'ZI',
      'MB',
      'SCs',
      'IC',
      'SNr',
      'VTA',
      'MRN',
      'SCm',
      'PAG',
      'APN',
      'NOT',
      'NPC',
      'PPT',
      'CUN',
      'RN',
      'AT',
      'SNc',
      'PPN',
      'IPN',
      'DR',
      'P',
      'NLL',
      'PSV',
      'PB',
      'SOC',
      'B',
      'DTN',
      'PCG',
      'PG',
      'PRNc',
      'SUT',
      'TRN',
      'V',
      'P5',
      'PC5',
      'CS',
      'LDT',
      'NI',
      'PRNr',
      'RPO',
      'MY',
      'DCO',
      'VCO',
      'CU',
      'SPVC',
      'SPVI',
      'VII',
      'DMX',
      'GRN',
      'IO',
      'IRN',
      'LRN',
      'MARN',
      'MDRN',
      'MDRNd',
      'MDRNv',
      'PARN',
      'PGRNd',
      'PGRNl',
      'PRP',
      'PPY',
      'LAV',
      'MV',
      'SPIV',
      'SUV',
      'RM',
      'CENT',
      'CUL',
      'CUL4, 5',
      'DEC',
      'FOTU',
      'PYR',
      'UVU',
      'NOD',
      'SIM',
      'AN',
      'PRM',
      'COPY',
      'PFL',
      'FL',
      'FN',
      'fiber tracts',
      'mlf',
      'll',
      'arb',
      'fa',
      'ccg',
      'fp',
      'ccb',
      'int',
      'or',
      'nst',
      'tspc',
      'cing',
      'alv',
      'fi',
      'fx',
      'dhc',
      'mfb',
      'pm',
      'mtt',
      'sm',
      'fr',
      'unknown'
    ]
    // const dataSourceKeywords = ['SEU', 'AIBS', 'Mouselight']

    // 初始化意图和参数
    // let searchIntent = 'unknown intent'
    let searchQuery = question.trim()
    let criteria = {}

    // 遍历搜索关键词，检查用户输入是否包含搜索意图

    if (searchIntent === 'search') {
    // 从用户输入中去除搜索关键词以获取搜索参数
    //   searchQuery = question.replace(keyword, '').trim()
      for (const keyword of altasKeywords) {
        if (question.includes(keyword)) {
          this.$set(criteria, 'brain_altas', [keyword])
        // criteria['brain_atlas'] = [keyword]
        }
      }
      for (const keyword of dataSourceKeywords) {
        if (question.includes(keyword)) {
          this.$set(criteria, 'data_source', [keyword])
        }
      }

      if (question.includes('AutoArbor')) {
        this.$set(criteria, 'has_ab', true)
      }
      if (question.includes('have reconstructed axon')) {
        this.$set(criteria, 'has_recon_axon', true)
      }
      if (question.includes('projection' || 'project to')) {
        for (const keyword of projKeywords) {
          const regex = new RegExp(`\\b${keyword}\\b`)
          if (regex.test(question)) {
            this.$set(criteria, 'proj_den_' + keyword + '_rela', [0, 1])
          }
        }
      } else {
        for (const keyword of brainRigionKeywords) {
          const regex = new RegExp(`\\b${keyword}\\b`)
          if (regex.test(question)) {
            this.$set(criteria, 'celltype', [keyword])
          }
        }
      }
      if (question.includes('have reconstructed dendrite')) {
        this.$set(criteria, 'has_recon_den', true)
      }
    }

    return { searchIntent, criteria }
  }
}
</script>

<style scoped>
.chat-window {
  width: 100%;
  border: 1px solid #ccc;
  padding: 10px;
}

.chat-messages {
  height: 400px;
  overflow-y: auto;
  border: 1px solid #eee;
  padding: 10px;
  margin-bottom: 5px;
}

.user-message {
  text-align: right;
  background-color: #ccf;
}

input {
  width: 100%;
  padding: 5px;
}
</style>
